"""Update user model

Revision ID: c8f93724707a
Revises: df1c57546259
Create Date: 2024-03-17 19:18:59.080398

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c8f93724707a'
down_revision: Union[str, None] = 'df1c57546259'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('national_id', sa.String(), nullable=False))
    op.add_column('users', sa.Column('address', sa.String(), nullable=False))
    op.add_column('users', sa.Column('state', sa.String(), nullable=False))
    op.alter_column('users', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('users', 'state')
    op.drop_column('users', 'address')
    op.drop_column('users', 'national_id')
    # ### end Alembic commands ###
