[GLOBAL]
pants_version = "2.19.0"
backend_packages = [
    "pants.backend.build_files.fmt.black",  
    "pants.backend.python",
    "pants.backend.python.lint.docformatter",
    "pants.backend.python.lint.black",
    "pants.backend.python.lint.flake8",
    "pants.backend.python.lint.isort",
    "pants.backend.python.typecheck.mypy",
]

[source]
root_paterns = [
    "/auth"
]

[python-setup]
interpreter_constraints = ["^3.12"]