[tool.poetry]
name = "auth"
version = "0.1.0"
description = ""
authors = ["Simon Florez <sflorezs1@eafit.edu.co>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
