"""Update document model

Revision ID: 54125f08fba1
Revises: 67b3e9dfd814
Create Date: 2024-03-20 23:33:54.299247

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '54125f08fba1'
down_revision: Union[str, None] = '67b3e9dfd814'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('email', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'email')
    # ### end Alembic commands ###
