"""Update document model

Revision ID: 7550c3e6a805
Revises: 54125f08fba1
Create Date: 2024-03-21 05:33:30.430940

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7550c3e6a805'
down_revision: Union[str, None] = '54125f08fba1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('documents', 'email',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.drop_column('documents', 'md5_hash')
    op.drop_column('documents', 'size')
    op.drop_column('documents', 'content_type')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('content_type', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('documents', sa.Column('size', sa.BIGINT(), autoincrement=False, nullable=True))
    op.add_column('documents', sa.Column('md5_hash', sa.VARCHAR(length=32), autoincrement=False, nullable=True))
    op.alter_column('documents', 'email',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    # ### end Alembic commands ###
